require 'alan.options'
require 'alan.plugins'
require 'alan.nvim-web-devicons'
require 'alan.indent-blankline'
require 'alan.theme'
require 'alan.bufferline'
require 'alan.nvim-tree'
require 'alan.keymaps'
require 'alan.lualine'
require 'alan.comment'
require 'alan.autopairs'
require 'alan.telescope'
require 'alan.lsp-zero'
-- require 'alan.noice'
-- require 'alan.mason'
-- require 'alan.null-ls'
