require 'user.options'
require 'user.plugins'
require 'user.nvim-web-devicons'
require 'user.indent-blankline'
require 'user.theme'
require 'user.bufferline'
require 'user.nvim-tree'
require 'user.keymaps'
require 'user.lualine'
require 'user.comment'
require 'user.autopairs'
require 'user.telescope'
require 'user.lsp-zero'
-- require 'user.noice'
-- require 'user.mason'
-- require 'user.null-ls'
